// Data for Soffy — categories, tastes, deals
// Bilingual strings (ES/EN)

window.I18N = {
  es: {
    welcome_tagline: "SWIPE TO SAVE",
    welcome_title_a: "Desliza.",
    welcome_title_b: "Ahorra.",
    welcome_title_c: "Repite.",
    welcome_sub: "Descubre descuentos que realmente te importan. Elige tus gustos, desliza a la derecha los que amas, ignora el resto.",
    get_started: "Empezar",
    already_account: "Ya tengo cuenta",
    back: "Atrás",
    continue: "Continuar",
    finish: "Empezar a swipear",
    step_of: "Paso {n} de {t}",
    onb1_title: "¿Qué te interesa?",
    onb1_sub: "Elige al menos 3 categorías. Podrás cambiarlas cuando quieras.",
    onb2_title: "Afinemos tus gustos",
    onb2_sub: "Toca todo lo que te guste. Entre más toques, mejor te conocemos.",
    onb3_title: "¿Dónde y cuánto?",
    onb3_sub: "Queremos mostrarte ofertas cerca y dentro de tu presupuesto.",
    onb4_title: "Listo para swipear",
    onb4_sub: "Hemos preparado tu feed personalizado. Toca el botón y empieza a descubrir.",
    loc_label: "Ubicación",
    loc_all: "Todas las ciudades",
    loc_cdmx: "Ciudad de México",
    loc_gdl: "Guadalajara",
    loc_mty: "Monterrey",
    budget_label: "Presupuesto",
    budget_low: "Económico",
    budget_low_hint: "Hasta $500",
    budget_med: "Medio",
    budget_med_hint: "$500 – $2,000",
    budget_high: "Premium",
    budget_high_hint: "Sin límite",
    deals_waiting: "{n} ofertas esperándote",
    based_on: "basadas en tus gustos",
    near_you: "Cerca de ti",
    trending: "Tendencia",
    top_match: "Top match",
    all_filter: "Todas",
    match_with: "MATCH",
    match_sub: "Guardamos este descuento en tus cupones. Úsalo antes de que expire.",
    view_coupon: "Ver cupón",
    keep_swiping: "Seguir swipeando",
    out_of_cards_title: "Por hoy, fin.",
    out_of_cards_sub: "Ya revisaste todas las ofertas que matchean. Vuelve mañana — siempre hay nuevos descuentos.",
    restart: "Ver de nuevo",
    match_percent: "{n}% match",
    ends_in: "Termina en {t}",
    km_away: "{n} km",
    now: "Hoy",
    nope: "Paso",
    like: "Me gusta",
    save: "Guardar",
  },
  en: {
    welcome_tagline: "SWIPE TO SAVE",
    welcome_title_a: "Swipe.",
    welcome_title_b: "Save.",
    welcome_title_c: "Repeat.",
    welcome_sub: "Discover deals that actually matter to you. Pick your tastes, swipe right on what you love, ignore the rest.",
    get_started: "Get started",
    already_account: "I have an account",
    back: "Back",
    continue: "Continue",
    finish: "Start swiping",
    step_of: "Step {n} of {t}",
    onb1_title: "What are you into?",
    onb1_sub: "Pick at least 3 categories. You can change them anytime.",
    onb2_title: "Fine-tune your tastes",
    onb2_sub: "Tap anything you like. The more you tap, the better we get.",
    onb3_title: "Where and how much?",
    onb3_sub: "We want to show you deals nearby and within your budget.",
    onb4_title: "Ready to swipe",
    onb4_sub: "Your personalized feed is ready. Hit the button and start discovering.",
    loc_label: "Location",
    loc_all: "All cities",
    loc_cdmx: "Mexico City",
    loc_gdl: "Guadalajara",
    loc_mty: "Monterrey",
    budget_label: "Budget",
    budget_low: "Budget",
    budget_low_hint: "Up to $500",
    budget_med: "Medium",
    budget_med_hint: "$500 – $2,000",
    budget_high: "Premium",
    budget_high_hint: "No limit",
    deals_waiting: "{n} deals waiting for you",
    based_on: "based on your tastes",
    near_you: "Near you",
    trending: "Trending",
    top_match: "Top match",
    all_filter: "All",
    match_with: "MATCH",
    match_sub: "We saved this deal to your coupons. Use it before it expires.",
    view_coupon: "View coupon",
    keep_swiping: "Keep swiping",
    out_of_cards_title: "That's it for today.",
    out_of_cards_sub: "You've reviewed all the matching deals. Check back tomorrow — there are always new ones.",
    restart: "Start over",
    match_percent: "{n}% match",
    ends_in: "Ends in {t}",
    km_away: "{n} km",
    now: "Today",
    nope: "Nope",
    like: "Like",
    save: "Save",
  }
};

window.CATEGORIES = [
  { id: "food", emoji: "🍕", name: { es: "Comida", en: "Food" }, count: 128 },
  { id: "fashion", emoji: "👕", name: { es: "Moda", en: "Fashion" }, count: 94 },
  { id: "tech", emoji: "💻", name: { es: "Tech", en: "Tech" }, count: 71 },
  { id: "travel", emoji: "✈️", name: { es: "Viajes", en: "Travel" }, count: 56 },
  { id: "cars", emoji: "🚗", name: { es: "Autos", en: "Cars" }, count: 23 },
  { id: "beauty", emoji: "💄", name: { es: "Belleza", en: "Beauty" }, count: 44 },
  { id: "ent", emoji: "🎬", name: { es: "Entretenimiento", en: "Entertainment" }, count: 62 },
  { id: "super", emoji: "🛒", name: { es: "Super", en: "Grocery" }, count: 39 },
  { id: "fitness", emoji: "🏋️", name: { es: "Fitness", en: "Fitness" }, count: 28 },
  { id: "home", emoji: "🛋️", name: { es: "Hogar", en: "Home" }, count: 51 },
  { id: "gaming", emoji: "🎮", name: { es: "Gaming", en: "Gaming" }, count: 37 },
];

// Tastes per category (subcategories)
window.TASTES = {
  food: [
    { id: "pizza", name: { es: "Pizza", en: "Pizza" } },
    { id: "sushi", name: { es: "Sushi", en: "Sushi" } },
    { id: "burger", name: { es: "Burgers", en: "Burgers" } },
    { id: "tacos", name: { es: "Tacos", en: "Tacos" } },
    { id: "ramen", name: { es: "Ramen", en: "Ramen" } },
    { id: "coffee", name: { es: "Café", en: "Coffee" } },
    { id: "healthy", name: { es: "Saludable", en: "Healthy" } },
    { id: "dessert", name: { es: "Postres", en: "Desserts" } },
    { id: "bbq", name: { es: "Parrilla", en: "BBQ" } },
    { id: "veggie", name: { es: "Vegetariano", en: "Vegetarian" } },
  ],
  fashion: [
    { id: "streetwear", name: { es: "Streetwear", en: "Streetwear" } },
    { id: "sneakers", name: { es: "Sneakers", en: "Sneakers" } },
    { id: "formal", name: { es: "Formal", en: "Formal" } },
    { id: "vintage", name: { es: "Vintage", en: "Vintage" } },
    { id: "athleisure", name: { es: "Deportiva", en: "Athleisure" } },
    { id: "luxury", name: { es: "Lujo", en: "Luxury" } },
    { id: "denim", name: { es: "Denim", en: "Denim" } },
    { id: "accessories", name: { es: "Accesorios", en: "Accessories" } },
  ],
  tech: [
    { id: "phones", name: { es: "Celulares", en: "Phones" } },
    { id: "laptops", name: { es: "Laptops", en: "Laptops" } },
    { id: "audio", name: { es: "Audio", en: "Audio" } },
    { id: "wearables", name: { es: "Wearables", en: "Wearables" } },
    { id: "cameras", name: { es: "Cámaras", en: "Cameras" } },
    { id: "gadgets", name: { es: "Gadgets", en: "Gadgets" } },
    { id: "smart-home", name: { es: "Smart home", en: "Smart home" } },
  ],
  travel: [
    { id: "hotels", name: { es: "Hoteles", en: "Hotels" } },
    { id: "flights", name: { es: "Vuelos", en: "Flights" } },
    { id: "beach", name: { es: "Playa", en: "Beach" } },
    { id: "city", name: { es: "Ciudades", en: "Cities" } },
    { id: "adventure", name: { es: "Aventura", en: "Adventure" } },
    { id: "cruises", name: { es: "Cruceros", en: "Cruises" } },
  ],
  cars: [
    { id: "rental", name: { es: "Renta", en: "Rental" } },
    { id: "service", name: { es: "Servicio", en: "Service" } },
    { id: "tires", name: { es: "Llantas", en: "Tires" } },
    { id: "accessories-car", name: { es: "Accesorios", en: "Accessories" } },
    { id: "new", name: { es: "Autos nuevos", en: "New cars" } },
  ],
  beauty: [
    { id: "spa", name: { es: "Spa", en: "Spa" } },
    { id: "haircut", name: { es: "Corte", en: "Haircut" } },
    { id: "nails", name: { es: "Uñas", en: "Nails" } },
    { id: "skincare", name: { es: "Skincare", en: "Skincare" } },
    { id: "makeup", name: { es: "Maquillaje", en: "Makeup" } },
    { id: "fragrance", name: { es: "Perfumes", en: "Fragrance" } },
  ],
  ent: [
    { id: "cinema", name: { es: "Cine", en: "Cinema" } },
    { id: "concerts", name: { es: "Conciertos", en: "Concerts" } },
    { id: "theater", name: { es: "Teatro", en: "Theater" } },
    { id: "bars", name: { es: "Bares", en: "Bars" } },
    { id: "streaming", name: { es: "Streaming", en: "Streaming" } },
    { id: "events", name: { es: "Eventos", en: "Events" } },
  ],
  super: [
    { id: "fresh", name: { es: "Frescos", en: "Fresh" } },
    { id: "snacks", name: { es: "Snacks", en: "Snacks" } },
    { id: "drinks", name: { es: "Bebidas", en: "Drinks" } },
    { id: "frozen", name: { es: "Congelados", en: "Frozen" } },
    { id: "organic", name: { es: "Orgánico", en: "Organic" } },
  ],
  fitness: [
    { id: "gym", name: { es: "Gym", en: "Gym" } },
    { id: "yoga", name: { es: "Yoga", en: "Yoga" } },
    { id: "crossfit", name: { es: "CrossFit", en: "CrossFit" } },
    { id: "supplements", name: { es: "Suplementos", en: "Supplements" } },
    { id: "gear", name: { es: "Equipo", en: "Gear" } },
  ],
  home: [
    { id: "furniture", name: { es: "Muebles", en: "Furniture" } },
    { id: "decor", name: { es: "Decoración", en: "Decor" } },
    { id: "kitchen", name: { es: "Cocina", en: "Kitchen" } },
    { id: "bedding", name: { es: "Recámara", en: "Bedding" } },
    { id: "appliances", name: { es: "Electrodom.", en: "Appliances" } },
  ],
  gaming: [
    { id: "consoles", name: { es: "Consolas", en: "Consoles" } },
    { id: "pc-games", name: { es: "PC games", en: "PC games" } },
    { id: "accessories-game", name: { es: "Accesorios", en: "Accessories" } },
    { id: "mobile-games", name: { es: "Móvil", en: "Mobile" } },
    { id: "merch", name: { es: "Merch", en: "Merch" } },
  ],
};

// Deals — each tagged with category and taste IDs so we can match
// gradient is fallback visual for the card image
window.DEALS = [
  { id: "d1", cat: "food", tastes: ["pizza"], brand: "Domino's", title: { es: "2x1 pizzas grandes", en: "2-for-1 large pizzas" }, discount: "50%", oldPrice: "$480", newPrice: "$240", distance: 1.2, endsIn: "4h", match: 98, grad: ["#ff6b1f", "#e85a10"] },
  { id: "d2", cat: "food", tastes: ["sushi"], brand: "Sushi Roll", title: { es: "Rollos 3x2 todo el día", en: "Rolls 3-for-2 all day" }, discount: "33%", oldPrice: "$390", newPrice: "$260", distance: 2.8, endsIn: "2d", match: 94, grad: ["#1d4ed8", "#3b82f6"] },
  { id: "d3", cat: "food", tastes: ["burger"], brand: "Shake Shack", title: { es: "Combo Smash + papas", en: "Smash combo + fries" }, discount: "25%", oldPrice: "$220", newPrice: "$165", distance: 0.8, endsIn: "6h", match: 91, grad: ["#ff8a3d", "#ff4d6d"] },
  { id: "d4", cat: "food", tastes: ["coffee"], brand: "Starbucks", title: { es: "Segundo café al 50%", en: "2nd coffee 50% off" }, discount: "50%", oldPrice: "$95", newPrice: "$47", distance: 0.3, endsIn: "3d", match: 89, grad: ["#14663a", "#22c55e"] },
  { id: "d5", cat: "food", tastes: ["tacos"], brand: "El Califa", title: { es: "Pastor 4x3", en: "Pastor 4-for-3" }, discount: "25%", oldPrice: "$180", newPrice: "$135", distance: 1.5, endsIn: "1d", match: 87, grad: ["#ff4d6d", "#ff6b1f"] },
  { id: "d6", cat: "food", tastes: ["ramen"], brand: "Ichiraku", title: { es: "Ramen + gyoza combo", en: "Ramen + gyoza combo" }, discount: "30%", oldPrice: "$250", newPrice: "$175", distance: 3.1, endsIn: "5d", match: 82, grad: ["#7e22ce", "#d946ef"] },

  { id: "d7", cat: "fashion", tastes: ["sneakers"], brand: "Nike", title: { es: "Air Max — 40% off", en: "Air Max — 40% off" }, discount: "40%", oldPrice: "$2,800", newPrice: "$1,680", distance: 4.2, endsIn: "2d", match: 96, grad: ["#0a1628", "#3b82f6"] },
  { id: "d8", cat: "fashion", tastes: ["streetwear"], brand: "H&M", title: { es: "Hoodies desde $299", en: "Hoodies from $299" }, discount: "35%", oldPrice: "$459", newPrice: "$299", distance: 2.1, endsIn: "4d", match: 88, grad: ["#111", "#ff6b1f"] },
  { id: "d9", cat: "fashion", tastes: ["denim"], brand: "Levi's", title: { es: "Jeans 2x1 en todas las tallas", en: "Jeans 2-for-1 all sizes" }, discount: "50%", oldPrice: "$1,200", newPrice: "$600", distance: 5.0, endsIn: "7d", match: 84, grad: ["#1e3a8a", "#60a5fa"] },
  { id: "d10", cat: "fashion", tastes: ["vintage"], brand: "Goodfellas Vintage", title: { es: "Todo lo vintage -30%", en: "Everything vintage -30%" }, discount: "30%", oldPrice: "$890", newPrice: "$623", distance: 3.4, endsIn: "3d", match: 79, grad: ["#7c2d12", "#ea580c"] },

  { id: "d11", cat: "tech", tastes: ["audio"], brand: "Sony", title: { es: "WH-1000XM5 Black Friday", en: "WH-1000XM5 Black Friday" }, discount: "35%", oldPrice: "$8,999", newPrice: "$5,849", distance: 0, endsIn: "1d", match: 93, grad: ["#0f172a", "#1d4ed8"] },
  { id: "d12", cat: "tech", tastes: ["phones"], brand: "iShop", title: { es: "iPhone 15 Pro -$4,000", en: "iPhone 15 Pro -$4,000" }, discount: "15%", oldPrice: "$28,999", newPrice: "$24,999", distance: 1.8, endsIn: "3d", match: 90, grad: ["#111", "#444"] },
  { id: "d13", cat: "tech", tastes: ["laptops"], brand: "Best Buy", title: { es: "MacBook Air M3 -25%", en: "MacBook Air M3 -25%" }, discount: "25%", oldPrice: "$32,499", newPrice: "$24,374", distance: 6.2, endsIn: "5d", match: 86, grad: ["#1e293b", "#64748b"] },
  { id: "d14", cat: "tech", tastes: ["gadgets"], brand: "Xiaomi", title: { es: "Robot aspiradora 40% off", en: "Robot vacuum 40% off" }, discount: "40%", oldPrice: "$4,500", newPrice: "$2,700", distance: 3.0, endsIn: "6d", match: 78, grad: ["#ea580c", "#fbbf24"] },

  { id: "d15", cat: "travel", tastes: ["hotels"], brand: "Booking", title: { es: "2 noches en Tulum -40%", en: "2 nights in Tulum -40%" }, discount: "40%", oldPrice: "$6,800", newPrice: "$4,080", distance: 0, endsIn: "10d", match: 95, grad: ["#0891b2", "#22d3ee"] },
  { id: "d16", cat: "travel", tastes: ["flights"], brand: "Volaris", title: { es: "Vuelos a Cancún $899", en: "Flights to Cancun $899" }, discount: "60%", oldPrice: "$2,200", newPrice: "$899", distance: 0, endsIn: "2d", match: 92, grad: ["#7c3aed", "#a78bfa"] },
  { id: "d17", cat: "travel", tastes: ["beach"], brand: "Palladium", title: { es: "All-inclusive 3 noches", en: "All-inclusive 3 nights" }, discount: "30%", oldPrice: "$14,500", newPrice: "$10,150", distance: 0, endsIn: "14d", match: 87, grad: ["#0369a1", "#0ea5e9"] },

  { id: "d18", cat: "cars", tastes: ["rental"], brand: "Hertz", title: { es: "Renta fin de semana -50%", en: "Weekend rental -50%" }, discount: "50%", oldPrice: "$1,800", newPrice: "$900", distance: 2.5, endsIn: "3d", match: 85, grad: ["#1e3a8a", "#3b82f6"] },
  { id: "d19", cat: "cars", tastes: ["service"], brand: "Petromax", title: { es: "Servicio completo -30%", en: "Full service -30%" }, discount: "30%", oldPrice: "$2,400", newPrice: "$1,680", distance: 4.7, endsIn: "7d", match: 72, grad: ["#444", "#ff6b1f"] },

  { id: "d20", cat: "beauty", tastes: ["spa"], brand: "Nuage Spa", title: { es: "Masaje 90 min + facial", en: "90-min massage + facial" }, discount: "45%", oldPrice: "$2,200", newPrice: "$1,210", distance: 1.9, endsIn: "5d", match: 91, grad: ["#be185d", "#ec4899"] },
  { id: "d21", cat: "beauty", tastes: ["haircut"], brand: "Tony&Guy", title: { es: "Corte + color 35% off", en: "Cut + color 35% off" }, discount: "35%", oldPrice: "$1,400", newPrice: "$910", distance: 2.2, endsIn: "6d", match: 83, grad: ["#a21caf", "#d946ef"] },

  { id: "d22", cat: "ent", tastes: ["cinema"], brand: "Cinépolis", title: { es: "Martes 2x1 VIP", en: "Tuesday 2-for-1 VIP" }, discount: "50%", oldPrice: "$220", newPrice: "$110", distance: 1.1, endsIn: "1d", match: 94, grad: ["#1e1b4b", "#6366f1"] },
  { id: "d23", cat: "ent", tastes: ["concerts"], brand: "Ticketmaster", title: { es: "Boletos 20% off", en: "Tickets 20% off" }, discount: "20%", oldPrice: "$1,500", newPrice: "$1,200", distance: 3.4, endsIn: "4d", match: 81, grad: ["#9333ea", "#e879f9"] },

  { id: "d24", cat: "super", tastes: ["fresh"], brand: "Walmart", title: { es: "Frutas y verduras -25%", en: "Fruits & veggies -25%" }, discount: "25%", oldPrice: "$800", newPrice: "$600", distance: 0.9, endsIn: "2d", match: 88, grad: ["#15803d", "#4ade80"] },

  { id: "d25", cat: "fitness", tastes: ["gym"], brand: "Smart Fit", title: { es: "3 meses al precio de 1", en: "3 months for the price of 1" }, discount: "66%", oldPrice: "$1,800", newPrice: "$600", distance: 1.3, endsIn: "3d", match: 92, grad: ["#14532d", "#84cc16"] },
  { id: "d26", cat: "fitness", tastes: ["yoga"], brand: "Yoga Studio", title: { es: "Pase ilimitado -40%", en: "Unlimited pass -40%" }, discount: "40%", oldPrice: "$1,500", newPrice: "$900", distance: 2.0, endsIn: "5d", match: 80, grad: ["#065f46", "#10b981"] },

  { id: "d27", cat: "home", tastes: ["furniture"], brand: "IKEA", title: { es: "Sala completa -30%", en: "Full living room -30%" }, discount: "30%", oldPrice: "$12,000", newPrice: "$8,400", distance: 7.8, endsIn: "6d", match: 86, grad: ["#1d4ed8", "#fbbf24"] },
  { id: "d28", cat: "home", tastes: ["kitchen"], brand: "Liverpool", title: { es: "Ollas KitchenAid -45%", en: "KitchenAid cookware -45%" }, discount: "45%", oldPrice: "$3,500", newPrice: "$1,925", distance: 4.1, endsIn: "4d", match: 78, grad: ["#991b1b", "#ef4444"] },

  { id: "d29", cat: "gaming", tastes: ["consoles"], brand: "GamePlanet", title: { es: "PS5 Slim + 2 juegos", en: "PS5 Slim + 2 games" }, discount: "18%", oldPrice: "$13,999", newPrice: "$11,500", distance: 5.2, endsIn: "8d", match: 95, grad: ["#0f172a", "#1d4ed8"] },
  { id: "d30", cat: "gaming", tastes: ["pc-games"], brand: "Steam", title: { es: "Top AAA -70% Spring Sale", en: "Top AAA -70% Spring Sale" }, discount: "70%", oldPrice: "$1,200", newPrice: "$360", distance: 0, endsIn: "11d", match: 97, grad: ["#1e293b", "#3b82f6"] },
  { id: "d31", cat: "gaming", tastes: ["accessories-game"], brand: "Razer", title: { es: "Mouse + teclado combo", en: "Mouse + keyboard combo" }, discount: "35%", oldPrice: "$3,200", newPrice: "$2,080", distance: 0, endsIn: "4d", match: 84, grad: ["#111", "#22c55e"] },
];
